const SET_LANGUAGE = 'SET_LANGUAGE';
const SET_FLOW = 'SET_FLOW';
const TOGGLE_MASK_LAYER = 'TOGGLE_MASK_LAYER';
const SET_MYKAD_INFO = 'SET_MYKAD_INFO';
const SET_PASSPORT_INFO = 'SET_PASSPORT_INFO';
const UPDATE_DIALOG = 'UPDATE_DIALOG';
const RESET_STORE = 'RESET_STORE';
const SET_EXCHANGE_RATE = 'SET_EXCHANGE_RATE';
const TOGGLE_MUTED = 'TOGGLE_MUTED';
const SET_THANKS_LANGUAGE = 'SET_THANKS_LANGUAGE';
const SET_FLOW_STATUS = 'SET_FLOW_STATUS';
const SET_EXCHANGE_RATE_NUM = 'SET_EXCHANGE_RATE_NUM';
const SET_TRANSACTION = 'SET_TRANSACTION';

export {
    SET_LANGUAGE,
    SET_FLOW,
    TOGGLE_MASK_LAYER,
    SET_MYKAD_INFO,
    SET_PASSPORT_INFO,
    UPDATE_DIALOG,
    RESET_STORE,
    SET_EXCHANGE_RATE,
    TOGGLE_MUTED,
    SET_THANKS_LANGUAGE,
    SET_FLOW_STATUS,
    SET_TRANSACTION,
    SET_EXCHANGE_RATE_NUM
}
